### ISSUE TITLE
Project direction of multicam_imu_calib

### ISSUE THREAD

**Issue by Alex-Beh** [berndpfrommer/multicam_imu_calib#1]
Hi @berndpfrommer,

Thanks for open-sourcing this project. I am interested in this project, and I can contribute if you need help. I would like to clarify some questions:

1. Are you aware of [Kalibr](https://github.com/ethz-asl/kalibr)? It is a visual-inertial calibration toolbox from ETH. How does this project differ from [Camera-IMU calibration](https://github.com/ethz-asl/kalibr/wiki/camera-imu-calibration)?
2. Could you share the calibration pipeline of this project? Does it use information from tagSLAM?
3. Can I calibrate the cameras and IMU on a mobile robot where I cannot freely move the platform to excite every axis?

**Comment by berndpfrommer** [comment]
1. Yes. Very much, used it bazilion times. As you can tell, this project has barely started. Here is how it will differ:
    - native ROS2 support
    - faster
    - simpler code base
    - support both online and from-bag calibration
    - aiming to become part of rosdistro, i.e. simple installation
    - covariances for calibration parameters
    - maybe GUI integration with rviz
 2. This will basically be a front-end to GTSAM. The tag detector will be separate. This code is written from scratch and has nothing to do with TagSLAM. Once I'm done with this project, converting TagSLAM to ROS2 is next.
 3. I will first finish camera calibration, then IMU calibration. I do *not* see any way to get extrinsic camera-imu calibration without moving the IMU.  In contrast to Kalibr, you will have to give initial guesses for all parameters, including the camera-imu extrinsics. This will give you the opportunity to specify those parts of the transform that you know from e.g. CAD drawings, and improve on the degrees of freedom that you can excite the robot about.

**Comment by Alex-Beh** [comment]
To clarify my third point, currently the issue I facing for camera-imu calibration with Kalibr is I must move the entire platform and exicite the 9DoF in order to get an accurate calibration result. It is quite easy if the platform is a drone or robot-rover. However if the camera and imu are mount on a heavy mobile robot such as MIR or Clearpath Husky, it is quite difficult to perform camera-imu calibration by Kalibr since I only can move the platform in a 2D plane.

So I would like to know whether multicam_imu_calib can handle this case?

Do you have an estimate timeline for this project to be functional?

**Comment by berndpfrommer** [comment]
No, I don't see a way how to calibrate a sensor that produces no signal.
Don't hold your breath for this project to complete. In a best case scenario it will be done by this summer. My advice: figure out how to rock your robot, and use Kalibr.
